### ISSUE TITLE
Infografia - Vasquez Reyes Gibran Jesus

### ISSUE THREAD

**Issue by GibranVasquez** [SistemasTecTlaxiaco/infografia-de-hilos-GibranVasquez#2]
https://drive.google.com/file/d/1pVSuJVRxrgXhkDLosChKuqQZX0-EvhZH/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
19 puntos

muy buena presentación cumple con todos los requisitos pero si le pudieras agregar un poco mas de información mejoraría en gran manera

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
